### ISSUE TITLE
all the controls except kick/clap are routed to the opposite color voice

### ISSUE THREAD

**Issue by x37v** [sam-schorb/orbits#1]
v1.1 if I start from the initial blank sequence, randomize the snare/tom, then alter the tune on the green voice, it actually affects the entries that are pink. the pink tune adjusts the entries that are green.
this same detail goes for the rim/clave and hat/shaker

**Comment by sam-schorb** [comment]
Thank you for checking it out so carefully. I hope you have some fun with it. You're right, the mappings were mixed up. It's fixed now so i'll mark this as closed.
